# Generated by Django 5.1.15 on 2026-07-01 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(db_index=True, max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Nuevo', 'Nuevo')], default='Regular', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('marca', models.CharField(blank=True, max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=200)),
                ('nro_serie', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('medidas', models.CharField(blank=True, max_length=100)),
                ('caracteristicas', models.CharField(blank=True, max_length=500)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('estado_verificacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Verificado', 'Verificado'), ('Faltante', 'Faltante')], default='Pendiente', max_length=20)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_verificados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.servicio')),
            ],
            options={
                'ordering': ['codigo_patrimonial'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.bien')),
                ('tomada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.CharField(blank=True, max_length=500)),
                ('observacion', models.TextField(blank=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='inventario.bien')),
                ('verificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
