# Generated by Django 5.1.15 on 2026-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='estado_verificacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('CONFORME', 'Conforme'), ('FALTANTE', 'Faltante'), ('CAMBIADO', 'Cambiado'), ('DAÑADO', 'Dañado')], default='Pendiente', max_length=20),
        ),
    ]
